app/expenses/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='home'),
]

app/mysite/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('expenses.urls'))
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

app/expenses/models.py
from django.db import models


class Transaction(models.Model):
    FIXED = 'FXD'
    VARIABLE = 'VAR'
    MODE_CHOICE = ((FIXED, 'Fixed'), (VARIABLE, 'Variable'))

    ESTIMATED = 'EST'
    REAL = 'RAL'
    STATE_CHOICE = ((ESTIMATED, 'Estimated'), (REAL, 'Real'))

    quantity = models.DecimalField(decimal_places=2, max_digits=8)
    category = models.ForeignKey('Category', on_delete=models.CASCADE)
    sub_category = models.ForeignKey('SubCategory', on_delete=models.CASCADE, null=True, blank=True)
    description = models.TextField(null=True, blank=True)
    mode = models.CharField(
        max_length=3,
        choices=MODE_CHOICE,
        default=VARIABLE
    )
    real_date = models.DateField(default=None, null=True, blank=True)
    state = models.CharField(
        max_length=3,
        choices=STATE_CHOICE,
        default=REAL
    )
    computable = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    @property
    def real(self):
        return self.real_date

    @property
    def no_computable(self):
        return 'NO COMPUTABLE' if not self.computable else ''

    @property
    def created(self):
        return self.created_at

    @property
    def updated(self):
        return self.updated_at


class Category(models.Model):
    name = models.CharField(max_length=20, unique=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name


class TransactionCategorySummary(Transaction):
    class Meta:
        proxy = True
        verbose_name = 'Transaction Category Summary'
        verbose_name_plural = 'Transactions Category Summary'


class SubCategory(models.Model):
    name = models.CharField(max_length=20, unique=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name


class Plan(models.Model):
    ENABLED = 'ENBL'
    DISABLED = 'DSBL'
    ACTIVE_CHOICE = ((ENABLED, 'Enabled'), (DISABLED, 'Disabled'))

    quantity = models.DecimalField(decimal_places=2, max_digits=8)
    category = models.ForeignKey('Category', on_delete=models.CASCADE)
    description = models.TextField(null=True, blank=True)
    date = models.DateField()
    active = models.CharField(
        max_length=4,
        choices=ACTIVE_CHOICE,
        default=ENABLED)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def created(self):
        return self.created_at

    def updated(self):
        return self.updated_at

app/expenses/forms.py
from django import forms
from .models import Transaction


class TransactionForm(forms.ModelForm):
    class Meta:
        model = Transaction
        fields = ('quantity', 'category', 'sub_category', 'mode', 'state', 'description')

app/expenses/views.py
import json
from datetime import datetime, timedelta
from decimal import Decimal

from django.db.models import Sum, Count
from django.http import HttpResponse
from django.shortcuts import redirect, render
from django.template import loader
from django.views.generic import ListView, CreateView, UpdateView, TemplateView

from .forms import TransactionForm
from .models import Transaction, Category, Plan


def index(request):
    qs = Transaction.objects.get_queryset()
    metrics = {
        'transaction_count': Count('id'),
        'quantity__sum': Sum('quantity'),
    }
    transactions_summary = list(
        qs.values('category__name').annotate(**metrics).order_by('-quantity__sum')
    )
    transactions_total = dict(
        qs.aggregate(**metrics)
    )
    context = {
        'summary': json.dumps(transactions_summary, cls=DecimalEncoder),
        'total': json.dumps(transactions_total, cls=DecimalEncoder),
    }
    return render(request, "index.html", context)


#####################
# extent json encoder
class DecimalEncoder(json.JSONEncoder):
    def default(self, obj):
        if isinstance(obj, Decimal):
            return float(obj)
        return json.JSONEncoder.default(self, obj)


def transaction_new(request):
    if request.method == "POST":
        form = TransactionForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('index')
    else:
        form = TransactionForm()
    context = {'form': form}
    template = loader.get_template('transaction_new.html')
    return HttpResponse(template.render(context, request))


##################################
# functions tool for page views
##################################

def transaction_variable_month(request):
    year_month = datetime.strptime(request.GET.get('month', datetime.now().strftime('%Y%m')), '%Y%m')
    context = {'month': datetime.strftime(year_month, '%B %Y')}
    template = loader.get_template('transaction_variable_month.html')
    return HttpResponse(template.render(context, request))


def subtract_one_month(datetime_0):
    """
    Move a datetime to previous month
    Args:
        datetime_0 (datetime):

    Returns:
        datetime
    """
    day = datetime_0.day
    month = datetime_0.month
    datetime_1 = datetime_0.replace(day=1)
    datetime_2 = datetime_1 - timedelta(days=1)

    try:
        datetime_3 = datetime_2.replace(day=day)
    except ValueError:
        if month - 1 == 2:
            day = 28
        if month - 1 in [4, 6, 9, 11]:
            day = 30
        datetime_3 = datetime_2.replace(day=day)

    return datetime_3


##################################
# Home page views
##################################

class HomePageView(TemplateView):
    template_name = 'home.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        month = self.request.GET.get('month')
        if month is None:
            current_date = datetime.now()
        else:
            current_date = datetime.strptime(month, '%Y%m')

        var_month_transaction = Transaction.objects.filter(
            mode='VAR',
            state='RAL',
            real_date__year=current_date.strftime('%Y'),
            real_date__month=current_date.strftime('%m')
        ).order_by('-real_date')
        context['var_month_transaction'] = var_month_transaction

        total_amount = var_month_transaction.aggregate(Sum('quantity'))['quantity__sum']
        total_amount = 0 if total_amount is None else total_amount
        context['total_amount'] = {'value': total_amount, 'percent': (total_amount * 100) / 500}

        fdx_month_transaction = Transaction.objects.filter(
            mode='FXD',
            state='RAL',
            real_date__year=current_date.strftime('%Y'),
            real_date__month=current_date.strftime('%m')
        ).order_by('-real_date')
        context['fdx_month_transaction'] = fdx_month_transaction

        fxd_total_amount = fdx_month_transaction.aggregate(Sum('quantity'))['quantity__sum']
        context['fxd_total_amount'] = fxd_total_amount

        sum_amount_categories = Transaction.objects.values('category__name').annotate(Sum('quantity')).filter(
            mode='VAR',
            state='RAL',
            real_date__year=current_date.strftime('%Y'),
            real_date__month=current_date.strftime('%m')
        ).order_by('-quantity__sum')
        context['sum_amount_categories'] = sum_amount_categories

        past_date = subtract_one_month(current_date)
        context['current_month'] = {'label': current_date.strftime('%B %Y'), 'link': current_date.strftime('%Y%m')}

        context['past_month'] = {'label': past_date.strftime('%B %Y'), 'link': past_date.strftime('%Y%m')}

        plans = Plan.objects.filter(active='ENBL')
        context['plans'] = plans

        return context


##################################
# Category views
##################################

class CategoryList(ListView):
    model = Category


class CategoryCreate(CreateView):
    model = Category
    fields = ['name']
    success_url = '/category'


class CategoryUpdate(UpdateView):
    model = Category
    fields = ['name']
    template_name_suffix = '_update_form'
    success_url = '/category'


################################
# PLan views
################################

class PlanList(ListView):
    model = Plan


class PlanCreate(CreateView):
    model = Plan
    fields = ['quantity', 'category', 'description', 'month_day', 'active']
    success_url = '/plan'

app/expenses/templates/bills/category_form.html
{% extends 'base.html' %}
{% load widget_tweaks %}

{% block content %}
<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pb-2 mb-3">
  <h2>New Category</h2>
  <div class="btn-group mr-2">
    <a href="{% url 'category_list' %}" class="btn btn-sm btn-outline-primary"> Category List </a>
  </div>
</div>

<div class="py-4 px-3 px-md-4">
  <form method="post">
    {% csrf_token %}

    {% for hidden_field in form.hidden_fields %}
    {{ hidden_field }}
    {% endfor %}

    {% if form.non_field_errors %}
    <div class="alert alert-danger" role="alert">
      {% for error in form.non_field_errors %}
      {{ error }}
      {% endfor %}
    </div>
    {% endif %}

    {% for field in form.visible_fields %}
    <div class="form-group">
      {{ field.label_tag }}

      {% if form.is_bound %}
        {% if field.errors %}
          {% render_field field class="form-control is-invalid" %}
          {% for error in field.errors %}
          <div class="invalid-feedback">
            {{ error }}
          </div>
          {% endfor %}
        {% else %}
          {% render_field field class="form-control is-valid" %}
        {% endif %}
      {% else %}
        {% render_field field class="form-control" %}
      {% endif %}

      {% if field.help_text %}
      <small class="form-text text-muted">{{ field.help_text }}</small>
      {% endif %}
    </div>
    {% endfor %}

    <button type="submit" class="btn btn-outline-primary">Submit</button>
  </form>
</div>

{% endblock %}

app/expenses/templates/bills/category_list.html
{% extends 'base.html' %}

{% block content %}
<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pb-2 mb-3">
  <h2>Category List</h2>
  <div class="btn-group mr-2">
    <a href="{% url 'category_new' %}" class="btn btn-sm btn-outline-primary"><span data-feather="plus"></span>Add
      Category</a>
  </div>
</div>

<div class="py-4 px-3 px-md-4">
  {% if object_list %}
  <div class="table-responsive">
    <table class="table table-striped table-sm">
      <thead>
      <tr>
        <th>Name</th>
      </tr>
      </thead>
      <tfoot>
      <tr>
        <th>Name</th>
      </tr>
      </tfoot>
      <tbody>
      {% for category in object_list %}
      <tr>
        <td><a href="{% url 'category_update' category.id %}">{{ category.name }}</a></td>
      </tr>
      {% endfor %}
      </tbody>
    </table>
  </div>
  {% else %}
  <p>No payment are available.</p>
  {% endif %}
</div>
{% endblock %}

app/expenses/templates/bills/category_update_form.html
{% extends 'base.html' %}
{% load widget_tweaks %}

{% block content %}
<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pb-2 mb-3">
  <h2>Update Category</h2>
  <div class="btn-group mr-2">
    <a href="{% url 'category_list' %}" class="btn btn-sm btn-outline-primary"> Category List </a>
  </div>
</div>

<div class="py-4 px-3 px-md-4">
  <form method="post">
    {% csrf_token %}

    {% for hidden_field in form.hidden_fields %}
    {{ hidden_field }}
    {% endfor %}

    {% if form.non_field_errors %}
    <div class="alert alert-danger" role="alert">
      {% for error in form.non_field_errors %}
      {{ error }}
      {% endfor %}
    </div>
    {% endif %}

    {% for field in form.visible_fields %}
    <div class="form-group">
      {{ field.label_tag }}

      {% if form.is_bound %}
        {% if field.errors %}
          {% render_field field class="form-control is-invalid" %}
          {% for error in field.errors %}
          <div class="invalid-feedback">
            {{ error }}
          </div>
          {% endfor %}
        {% else %}
          {% render_field field class="form-control is-valid" %}
        {% endif %}
      {% else %}
        {% render_field field class="form-control" %}
      {% endif %}

      {% if field.help_text %}
      <small class="form-text text-muted">{{ field.help_text }}</small>
      {% endif %}
    </div>
    {% endfor %}

    <button type="submit" class="btn btn-outline-primary">Submit</button>
  </form>
</div>

{% endblock %}

app/expenses/templates/bills/plan_form.html
{% extends 'base.html' %}
{% load widget_tweaks %}

{% block content %}
<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pb-2 mb-3">
  <h2>New PLan</h2>
  <div class="btn-group mr-2">
    <a href="{% url 'plan_list' %}" class="btn btn-sm btn-outline-primary"> PLan List </a>
  </div>
</div>

<div class="py-4 px-3 px-md-4">
  <form method="post">
    {% csrf_token %}

    {% for hidden_field in form.hidden_fields %}
    {{ hidden_field }}
    {% endfor %}

    {% if form.non_field_errors %}
    <div class="alert alert-danger" role="alert">
      {% for error in form.non_field_errors %}
      {{ error }}
      {% endfor %}
    </div>
    {% endif %}

    {% for field in form.visible_fields %}
    <div class="form-group">
      {{ field.label_tag }}

      {% if form.is_bound %}
        {% if field.errors %}
          {% render_field field class="form-control is-invalid" %}
          {% for error in field.errors %}
          <div class="invalid-feedback">
            {{ error }}
          </div>
          {% endfor %}
        {% else %}
          {% render_field field class="form-control is-valid" %}
        {% endif %}
      {% else %}
        {% render_field field class="form-control" %}
      {% endif %}

      {% if field.help_text %}
      <small class="form-text text-muted">{{ field.help_text }}</small>
      {% endif %}
    </div>
    {% endfor %}

    <button type="submit" class="btn btn-outline-primary">Submit</button>
  </form>
</div>

{% endblock %}

app/expenses/templates/bills/plan_list.html
{% extends 'base.html' %}

{% block content %}
<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pb-2 mb-3">
  <h2>PLan List</h2>
  <div class="btn-group mr-2">
    <a href="{% url 'plan_new' %}" class="btn btn-sm btn-outline-primary"><span data-feather="plus"></span>Add
      plan</a>
  </div>
</div>

<div class="py-4 px-3 px-md-4">
  {% if object_list %}
  <div class="table-responsive">
    <table class="table table-striped table-sm">
      <thead>
      <tr>
        <th>month_day</th>
        <th>quantity</th>
        <th>category</th>
        <th>description</th>
        <th>active</th>
      </tr>
      </thead>
      <tfoot>
      <tr>
        <th>month_day</th>
        <th>quantity</th>
        <th>category</th>
        <th>description</th>
        <th>active</th>
      </tr>
      </tfoot>
      <tbody>
      {% for item in object_list %}
      <tr>
        <td>{{ item.month_day }}</td>
        <td><a href="{% url 'category_update' item.id %}">{{ item.quantity }}</a></td>
        <td>{{ item.category }}</td>
        <td>{{ item.description}}</td>
        <td>{{ item.get_active_display}}</td>
      </tr>
      {% endfor %}
      </tbody>
    </table>
  </div>
  {% else %}
  <p>No payment are available.</p>
  {% endif %}
</div>
{% endblock %}